#!/bin/bash

export XAUTHORITY=/home/kazuya/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

BATT_STATUS=$1
BATT_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')

if [ $BATT_STATUS -eq 1 ]
then
	dunstify -u low -r 9996 "Charging" "${BATT_LEVEL}% charged" -t 5000 -i battery-charge
	/usr/bin/sudo -u kazuya /usr/bin/paplay --server=/run/user/1000/pulse/native /home/kazuya/.dotfiles/sources/insert.wav > /dev/null 2>&1
elif [ $BATT_STATUS -eq 0 ]
then
	dunstify -u low -r 9996 "Discharging" "${BATT_LEVEL}% remaining" -t 5000 -i battery-charge
	/usr/bin/sudo -u kazuya /usr/bin/paplay --server=/run/user/1000/pulse/native /home/kazuya/.dotfiles/sources/remove.wav > /dev/null 2>&1
fi
