#! /bin/bash
ln -s ~/.dotfiles/.bash_profile $HOME/.bash_profile
ln -s ~/.dotfiles/.bashrc $HOME/.bashrc
ln -s ~/.dotfiles/.gitconfig $HOME/.gitconfig
ln -s ~/.dotfiles/.xinitrc $HOME/.xinitrc
ln -s ~/.dotfiles/.Xresources $HOME/.Xresources
ln -s ~/.dotfiles/cava $HOME/.config/cava/config
ln -s ~/.dotfiles/config.rasi $HOME/.config/rofi/config.rasi
ln -s ~/.dotfiles/rounded-red-dark.rasi $HOME/.config/rofi/rounded-red-dark.rasi
ln -s ~/.dotfiles/rounded-common.rasi $HOME/.config/rofi/rounded-common.rasi
ln -s ~/.dotfiles/i3conf $HOME/.config/i3/config
ln -s ~/.dotfiles/i3statusconf $HOME/.config/i3status/config
ln -s ~/.dotfiles/kitty.conf $HOME/.config/kitty/kitty.conf
ln -s ~/.dotfiles/neofetch.conf $HOME/.config/neofetch/config.conf
ln -s ~/.dotfiles/picom.conf $HOME/.config/picom/picom.conf
ln -s ~/.dotfiles/polybar.ini $HOME/.config/polybar/config.ini
ln -s ~/.dotfiles/dunstrc $HOME/.config/dunst/dunstrc
ln -s ~/.dotfiles/betterlockscreenrc $HOME/.config/betterlockscreenrc
ln -s ~/.dotfiles/eww.yuck $HOME/.config/eww/eww.yuck
ln -s ~/.dotfiles/eww.scss $HOME/.config/eww/eww.scss
ln -s ~/.dotfiles/.vimrc $HOME/.vimrc
